#!/usr/bin/perl
open(INFILE, "<", "/home/soren/.conky/notes.md");
open(OUTFILE, ">", "/home/soren/.conky/notes.conky");

for(<INFILE>){
    s/^#\s/\$\{color #D0D032}/;
    s/\n/\$color\n/;
    print OUTFILE;
}

close(INFILE);
close(OUTFILE);
